#!/bin/sh

GF3_HOME=/usr/share/glassfish3
USER=glassfish

DOMAINS_HOME=/var/lib/glassfish3
LOGS_DIR=/var/log/glassfish3

if [ "$1" = "purge" ] ; then
  update-rc.d glassfish3 remove >/dev/null
fi

if [ -d "$DOMAINS_HOME" ]; then
  echo "removing domains directory"
  sudo rm -rf $DOMAINS_HOME
fi

if [ -d "$LOGS_DIR" ]; then
  echo "removing logs directory"
  sudo rm -rf $LOGS_DIR
fi

if [ -d "$GF3_HOME" ]; then
  echo "removing server directory"
  sudo rm -rf $GF3_HOME
fi

if [ -n "$(getent passwd glassfish)" ]; then
  echo "removing the user and group '$USER'"
  sudo deluser --system $USER
fi

